# Variables for Proxmox VM provisioning with Terraform and Packer
# ==============================================================================
# Packer needs its variables defined in its own .hcl file. They can share
# The terraform.tfvars file, but the .hcl extension is for packer build variables, and command:
# This is a bit redundant, but its the more DRY way right now. See packer.pkrvars.hcl for the variables specific to packer builds.

variable "karakeep_meili_master_key" {
  type        = string
  description = "A random secret string used by MeiliSearch to secure the master key for Karakeep."
  sensitive   = true
}
variable "karakeep_nextauth_secret" {
  type        = string
  description = "A random secret string used by NextAuth to encrypt tokens and secure sessions for Karakeep."
  sensitive   = true
}

variable "grafana_api_key" {
  type        = string
  description = "Grafana API Key - Enables homepage widget."
  sensitive   = true
}

variable "grafana_username" {
  type        = string
  description = "the grana username"
  default     = "admin"
  sensitive   = false
}

variable "grafana_password" {
  type        = string
  description = "the grana password"
  sensitive   = true
}

variable "proxmox_endpoint" {
  type        = string
  description = "The full HTTPS URL API endpoint for the Proxmox VE host."
  default     = "https://192.168.50.200:8006/"
}

# Use this for Terraform
variable "proxmox_api_token" {
  type        = string
  description = "The complete concatenated Proxmox API token ID and Secret string."
  sensitive   = true
}

variable "proxmox_api_user" {
  type        = string
  description = "The Proxmox API user for the token. Typically in the format 'username@realm'."
  sensitive   = false
}

# Packer needs these as individual components
variable "proxmox_api_token_id" {
  type    = string
  default = "root@pam!packer"
}

variable "proxmox_api_token_secret" {
  type      = string
  sensitive = true
}

variable "cloudflare_tunnel_token" {
  type        = string
  description = "Tunnel token generated by Cloudflare Zero Trust."
  sensitive   = true
}

variable "cloudflare_tunnel_id" {
  type        = string
  description = "Cloudflare Tunnel ID for the specific tunnel."
  sensitive   = true
}

variable "cloudflare_account_id" {
  type        = string
  description = "Cloudflare Account ID associated with the tunnel."
  sensitive   = true

}

variable "cloudflare_api_token" {
  type        = string
  description = "Cloudflare API token for managing tunnels."
  sensitive   = true
}

variable "cloudflare_dns_api_token" {
  type        = string
  description = "Cloudflare DNS API token for enabling https traffic over local network"
  sensitive   = true
}


variable "tailscale_auth_key" {
  type        = string
  description = "Reusable or Ephemeral Tailscale Authentication Key for auto-joining the mesh"
  sensitive   = true
}

variable "tailscale_api_token" {
  type        = string
  description = "Tailscale API Token for pulling device metadata and displaying it on the homepage widget"
  sensitive   = true
}

variable "tailscale_device_id_nas" {
  type        = string
  description = "The Tailscale Device ID for the NAS VM, used to pull specific metadata for the homepage widget."
  sensitive   = true

}

variable "tailscale_device_id_mac" {
  type        = string
  description = "The Tailscale Device ID for the Macbook Pro, used to pull specific metadata for the homepage widget."
  sensitive   = true

}

variable "proxmox_template_vm_id" {
  type        = string
  description = "The VM ID of the Proxmox template to clone for worker nodes."
  default     = "777"
}

variable "proxmox_node_name" {
  type        = string
  description = "The name of the Proxmox node to target for VM deployments."
  default     = "mothership"
}

# Having a bunch of IPs ins't ideal, but this is a quick and dirty way to get the job done without needing to write a custom script or Ansible playbook for this step.

variable "proxmox_host_ip" {
  type        = string
  description = "The IP address of the Proxmox host."
  default     = "192.168.50.200"
}


variable "k3s_manager_ip" {
  type        = string
  description = "The IP address of the K3s control manager node for worker registration. Match this IP with the KUBECONFIG"
  default     = "192.168.50.185" # 🎯 Formatted to point directly to the static manager node address
}

variable "default_gateway_ip" {
  type        = string
  description = "The network default gateway."
  default     = "192.168.50.1"
}

variable "http_bind_address_ip" {
  type        = string
  description = "The IP of the machine from which packer hcl and terraform will be executed from."
  default     = "192.168.50.55"
}

variable "worker_count" {
  type        = number
  description = "The number of worker nodes to provision in the cluster."
  default     = 2
}

variable "k3s_share_token" {
  type        = string
  description = "The join token generated by the K3s control plane server."
  sensitive   = true
}

# ==============================================================================
# 🎯 DYNAMIC HOMELAB SECRETS MAP (EXTRACTED FROM INSECURE PLAIN TEXT YAMLS)
# ==============================================================================

variable "pihole_admin_password" {
  type        = string
  description = "Administrative override credential password for the Pi-hole cluster dashboard."
  sensitive   = true
}

variable "pihole_api_key" {
  type        = string
  description = "Api token to enable widget access"
}

variable "proxmox_vm_auditor_password" {
  type        = string
  description = "Password for the Proxmox VM auditor user. Will be used to power the Homepage Widgets that pull data from the Proxmox API."
  sensitive   = true
}
